// <auto-generated />
using System;
using AgroApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgroApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AgroAppDbContext))]
    [Migration("20260708235759_SyncPendingSchema")]
    partial class SyncPendingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgroApp.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("alert_type");

                    b.Property<Guid?>("CropId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_id");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid?>("PlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("plot_id");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("CropId")
                        .HasDatabaseName("ix_alerts_crop_id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_alerts_device_id");

                    b.HasIndex("PlotId")
                        .HasDatabaseName("ix_alerts_plot_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_alerts_tenant_id");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metric");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operator");

                    b.Property<Guid?>("PlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("plot_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("numeric")
                        .HasColumnName("threshold");

                    b.HasKey("Id")
                        .HasName("pk_alert_rules");

                    b.HasIndex("PlotId")
                        .HasDatabaseName("ix_alert_rules_plot_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_alert_rules_tenant_id");

                    b.ToTable("alert_rules", (string)null);
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.CostEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CropId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.HasKey("Id")
                        .HasName("pk_cost_entries");

                    b.HasIndex("CropId")
                        .HasDatabaseName("ix_cost_entries_crop_id");

                    b.ToTable("cost_entries", (string)null);
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.Crop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CropType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("crop_type");

                    b.Property<DateOnly?>("EstimatedHarvest")
                        .HasColumnType("date")
                        .HasColumnName("estimated_harvest");

                    b.Property<DateOnly?>("HarvestedAt")
                        .HasColumnType("date")
                        .HasColumnName("harvested_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("PlantedAt")
                        .HasColumnType("date")
                        .HasColumnName("planted_at");

                    b.Property<Guid>("PlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("plot_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Variety")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("variety");

                    b.Property<decimal?>("YieldKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("yield_kg");

                    b.HasKey("Id")
                        .HasName("pk_crops");

                    b.HasIndex("PlotId")
                        .HasDatabaseName("ix_crops_plot_id");

                    b.ToTable("crops", (string)null);
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.CropImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AiAnalyzedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ai_analyzed_at");

                    b.Property<float?>("AiConfidence")
                        .HasColumnType("real")
                        .HasColumnName("ai_confidence");

                    b.Property<string>("AiDiagnosis")
                        .HasColumnType("text")
                        .HasColumnName("ai_diagnosis");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CropId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_id");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<DateTime?>("TakenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taken_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_crop_images");

                    b.HasIndex("CropId")
                        .HasDatabaseName("ix_crop_images_crop_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_crop_images_user_id");

                    b.ToTable("crop_images", (string)null);
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AreaHa")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("area_ha");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double?>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_farms");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_farms_owner_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_farms_tenant_id");

                    b.ToTable("farms", (string)null);
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.FcmToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("platform");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_fcm_tokens");

                    b.HasIndex("UserId", "Token")
                        .IsUnique()
                        .HasDatabaseName("ix_fcm_tokens_user_id_token");

                    b.ToTable("fcm_tokens", (string)null);
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.FertilizationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CropId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_id");

                    b.Property<decimal?>("DoseKgHa")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("dose_kg_ha");

                    b.Property<string>("Method")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("method");

                    b.Property<DateOnly?>("NextApplication")
                        .HasColumnType("date")
                        .HasColumnName("next_application");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("product_type");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<decimal?>("TotalKg")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("total_kg");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_fertilization_logs");

                    b.HasIndex("CropId")
                        .HasDatabaseName("ix_fertilization_logs_crop_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_fertilization_logs_task_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_fertilization_logs_user_id");

                    b.ToTable("fertilization_logs", (string)null);
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.IrrigationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CropId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_id");

                    b.Property<int?>("DurationMin")
                        .HasColumnType("integer")
                        .HasColumnName("duration_min");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("method");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal?>("VolumeLiters")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("volume_liters");

                    b.HasKey("Id")
                        .HasName("pk_irrigation_logs");

                    b.HasIndex("CropId")
                        .HasDatabaseName("ix_irrigation_logs_crop_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_irrigation_logs_task_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_irrigation_logs_user_id");

                    b.ToTable("irrigation_logs", (string)null);
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.LaborLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("activity_type");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CropId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_id");

                    b.Property<decimal?>("HoursWorked")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("hours_worked");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("WorkersCount")
                        .HasColumnType("integer")
                        .HasColumnName("workers_count");

                    b.HasKey("Id")
                        .HasName("pk_labor_logs");

                    b.HasIndex("CropId")
                        .HasDatabaseName("ix_labor_logs_crop_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_labor_logs_task_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_labor_logs_user_id");

                    b.ToTable("labor_logs", (string)null);
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.PhenologyStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CropId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_id");

                    b.Property<DateOnly?>("EndedAt")
                        .HasColumnType("date")
                        .HasColumnName("ended_at");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("boolean")
                        .HasColumnName("is_custom");

                    b.Property<string>("Observations")
                        .HasColumnType("text")
                        .HasColumnName("observations");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stage_name");

                    b.Property<int>("StageOrder")
                        .HasColumnType("integer")
                        .HasColumnName("stage_order");

                    b.Property<DateOnly>("StartedAt")
                        .HasColumnType("date")
                        .HasColumnName("started_at");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_phenology_stages");

                    b.HasIndex("CropId")
                        .HasDatabaseName("ix_phenology_stages_crop_id");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_phenology_stages_template_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_phenology_stages_tenant_id");

                    b.ToTable("phenology_stages", (string)null);
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.PhenologyTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CropType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("crop_type");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("icon");

                    b.Property<int>("MaxDays")
                        .HasColumnType("integer")
                        .HasColumnName("max_days");

                    b.Property<int>("MinDays")
                        .HasColumnType("integer")
                        .HasColumnName("min_days");

                    b.Property<string>("Recommendations")
                        .HasColumnType("text")
                        .HasColumnName("recommendations");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stage_name");

                    b.Property<int>("StageOrder")
                        .HasColumnType("integer")
                        .HasColumnName("stage_order");

                    b.HasKey("Id")
                        .HasName("pk_phenology_templates");

                    b.ToTable("phenology_templates", (string)null);
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.Plot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AreaHa")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("area_ha");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<string>("GeoJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("geojson");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("SoilType")
                        .HasColumnType("text")
                        .HasColumnName("soil_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_plots");

                    b.HasIndex("FarmId")
                        .HasDatabaseName("ix_plots_farm_id");

                    b.ToTable("plots", (string)null);
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.SensorDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("BatteryPct")
                        .HasColumnType("integer")
                        .HasColumnName("battery_pct");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_code");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_type");

                    b.Property<string>("FirmwareVer")
                        .HasColumnType("text")
                        .HasColumnName("firmware_ver");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double?>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<Guid>("PlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("plot_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sensor_devices");

                    b.HasIndex("PlotId")
                        .HasDatabaseName("ix_sensor_devices_plot_id");

                    b.ToTable("sensor_devices", (string)null);
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.SensorReading", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<decimal?>("Ec")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("ec");

                    b.Property<decimal?>("HumidityAir")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("humidity_air");

                    b.Property<decimal?>("HumiditySoil")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("humidity_soil");

                    b.Property<decimal?>("Luminosity")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("luminosity");

                    b.Property<decimal?>("Ph")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("ph");

                    b.Property<decimal?>("RainMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("rain_mm");

                    b.Property<decimal?>("Temperature")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("temperature");

                    b.HasKey("Id", "RecordedAt")
                        .HasName("pk_sensor_readings");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_sensor_readings_device_id");

                    b.ToTable("sensor_readings", (string)null);
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CropId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("PlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("plot_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("task_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasIndex("AssignedTo")
                        .HasDatabaseName("ix_tasks_assigned_to");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_tasks_created_by");

                    b.HasIndex("CropId")
                        .HasDatabaseName("ix_tasks_crop_id");

                    b.HasIndex("PlotId")
                        .HasDatabaseName("ix_tasks_plot_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tasks_tenant_id");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.TaskOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("shift");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_task_occurrences");

                    b.HasIndex("AssignedTo")
                        .HasDatabaseName("ix_task_occurrences_assigned_to");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_task_occurrences_template_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_task_occurrences_tenant_id");

                    b.ToTable("task_occurrences", (string)null);
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.TaskTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CropId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("PlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("plot_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<string>("RecurrenceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("recurrence_type");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("shift");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("task_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WeekDays")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("week_days");

                    b.HasKey("Id")
                        .HasName("pk_task_templates");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_task_templates_created_by");

                    b.HasIndex("CropId")
                        .HasDatabaseName("ix_task_templates_crop_id");

                    b.HasIndex("PlotId")
                        .HasDatabaseName("ix_task_templates_plot_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_task_templates_tenant_id");

                    b.ToTable("task_templates", (string)null);
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("free")
                        .HasColumnName("plan");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_id_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.Alert", b =>
                {
                    b.HasOne("AgroApp.Domain.Entities.Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_alerts_crops_crop_id");

                    b.HasOne("AgroApp.Domain.Entities.SensorDevice", "Device")
                        .WithMany("Alerts")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_alerts_sensor_devices_device_id");

                    b.HasOne("AgroApp.Domain.Entities.Plot", "Plot")
                        .WithMany()
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_alerts_plots_plot_id");

                    b.HasOne("AgroApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_tenants_tenant_id");

                    b.Navigation("Crop");

                    b.Navigation("Device");

                    b.Navigation("Plot");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.AlertRule", b =>
                {
                    b.HasOne("AgroApp.Domain.Entities.Plot", "Plot")
                        .WithMany()
                        .HasForeignKey("PlotId")
                        .HasConstraintName("fk_alert_rules_plots_plot_id");

                    b.HasOne("AgroApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alert_rules_tenants_tenant_id");

                    b.Navigation("Plot");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.CostEntry", b =>
                {
                    b.HasOne("AgroApp.Domain.Entities.Crop", "Crop")
                        .WithMany("CostEntries")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cost_entries_crops_crop_id");

                    b.Navigation("Crop");
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.Crop", b =>
                {
                    b.HasOne("AgroApp.Domain.Entities.Plot", "Plot")
                        .WithMany("Crops")
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_crops_plots_plot_id");

                    b.Navigation("Plot");
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.CropImage", b =>
                {
                    b.HasOne("AgroApp.Domain.Entities.Crop", "Crop")
                        .WithMany("CropImages")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_crop_images_crops");

                    b.HasOne("AgroApp.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_crop_images_users");

                    b.Navigation("Crop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.Farm", b =>
                {
                    b.HasOne("AgroApp.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_farms_users_owner_id");

                    b.HasOne("AgroApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Farms")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_farms_tenants_tenant_id");

                    b.Navigation("Owner");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.FcmToken", b =>
                {
                    b.HasOne("AgroApp.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fcm_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.FertilizationLog", b =>
                {
                    b.HasOne("AgroApp.Domain.Entities.Crop", "Crop")
                        .WithMany("FertilizationLogs")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fertilization_logs_crops_crop_id");

                    b.HasOne("AgroApp.Domain.Entities.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_fertilization_logs_tasks_task_id");

                    b.HasOne("AgroApp.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fertilization_logs_users_user_id");

                    b.Navigation("Crop");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.IrrigationLog", b =>
                {
                    b.HasOne("AgroApp.Domain.Entities.Crop", "Crop")
                        .WithMany("IrrigationLogs")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_irrigation_logs_crops_crop_id");

                    b.HasOne("AgroApp.Domain.Entities.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_irrigation_logs_tasks_task_id");

                    b.HasOne("AgroApp.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_irrigation_logs_users_user_id");

                    b.Navigation("Crop");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.LaborLog", b =>
                {
                    b.HasOne("AgroApp.Domain.Entities.Crop", "Crop")
                        .WithMany("LaborLogs")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_labor_logs_crops_crop_id");

                    b.HasOne("AgroApp.Domain.Entities.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_labor_logs_tasks_task_id");

                    b.HasOne("AgroApp.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_labor_logs_users_user_id");

                    b.Navigation("Crop");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.PhenologyStage", b =>
                {
                    b.HasOne("AgroApp.Domain.Entities.Crop", "Crop")
                        .WithMany("PhenologyStages")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_phenology_stages_crops_crop_id");

                    b.HasOne("AgroApp.Domain.Entities.PhenologyTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_phenology_stages_phenology_templates_template_id");

                    b.HasOne("AgroApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_phenology_stages_tenants_tenant_id");

                    b.Navigation("Crop");

                    b.Navigation("Template");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.Plot", b =>
                {
                    b.HasOne("AgroApp.Domain.Entities.Farm", "Farm")
                        .WithMany("Plots")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plots_farms_farm_id");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("AgroApp.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.SensorDevice", b =>
                {
                    b.HasOne("AgroApp.Domain.Entities.Plot", "Plot")
                        .WithMany("SensorDevices")
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sensor_devices_plots_plot_id");

                    b.Navigation("Plot");
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.SensorReading", b =>
                {
                    b.HasOne("AgroApp.Domain.Entities.SensorDevice", "Device")
                        .WithMany("SensorReadings")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sensor_readings_sensor_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("AgroApp.Domain.Entities.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_users_assigned_to");

                    b.HasOne("AgroApp.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_users_created_by");

                    b.HasOne("AgroApp.Domain.Entities.Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tasks_crops_crop_id");

                    b.HasOne("AgroApp.Domain.Entities.Plot", "Plot")
                        .WithMany()
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tasks_plots_plot_id");

                    b.HasOne("AgroApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_tenants_tenant_id");

                    b.Navigation("Assignee");

                    b.Navigation("Creator");

                    b.Navigation("Crop");

                    b.Navigation("Plot");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.TaskOccurrence", b =>
                {
                    b.HasOne("AgroApp.Domain.Entities.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_task_occurrences_users_assigned_to");

                    b.HasOne("AgroApp.Domain.Entities.TaskTemplate", "Template")
                        .WithMany("Occurrences")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_occurrences_task_templates_template_id");

                    b.HasOne("AgroApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_occurrences_tenants_tenant_id");

                    b.Navigation("Assignee");

                    b.Navigation("Template");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.TaskTemplate", b =>
                {
                    b.HasOne("AgroApp.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_templates_users_created_by");

                    b.HasOne("AgroApp.Domain.Entities.Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_task_templates_crops_crop_id");

                    b.HasOne("AgroApp.Domain.Entities.Plot", "Plot")
                        .WithMany()
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_task_templates_plots_plot_id");

                    b.HasOne("AgroApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_templates_tenants_tenant_id");

                    b.Navigation("Creator");

                    b.Navigation("Crop");

                    b.Navigation("Plot");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.User", b =>
                {
                    b.HasOne("AgroApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.Crop", b =>
                {
                    b.Navigation("CostEntries");

                    b.Navigation("CropImages");

                    b.Navigation("FertilizationLogs");

                    b.Navigation("IrrigationLogs");

                    b.Navigation("LaborLogs");

                    b.Navigation("PhenologyStages");
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.Farm", b =>
                {
                    b.Navigation("Plots");
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.Plot", b =>
                {
                    b.Navigation("Crops");

                    b.Navigation("SensorDevices");
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.SensorDevice", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("SensorReadings");
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.TaskTemplate", b =>
                {
                    b.Navigation("Occurrences");
                });

            modelBuilder.Entity("AgroApp.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Farms");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
